name = "athena"
compatibility_date = "2024-04-05"
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "KV"
id = "285b7e8ee6534733bbfeb4673d66b4e1"

[[d1_databases]]
binding = "DB"
database_name = "athena-db"
database_id = "bc9dacc0-a6d9-4b1d-8ca0-f3d0d46eebff"
migrations_dir = "src/db/migrations"
