name = "athena"
compatibility_date = "2024-04-05"
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "KV"
id = "f2274cb066714e51ba6fc9087b1989bc"

[[d1_databases]]
binding = "DB"
database_name = "athena-db"
database_id = "fa6a5a4f-ee91-4d3e-9183-3f90e9f0a464"
migrations_dir = "src/db/migrations"
